#!/usr/bin/env bash

set -e

# name may contain hyphens
name="$(basename $(cd "$(dirname $(dirname "$0"))"; pwd -P))"
underscore_name=${name//-/_}
spaceless_name=${name//-/}

if [[ "$OSTYPE" == "darwin"* ]]; then
    sedflags=(-i "")
else
    sedflags=(-i)
fi

for file in $(find . -not \( -name .git -prune \) -not \( -name __pycache__ -prune \) -a -type f); do
    file_name=$(basename "$file")
    case $file_name in
        rename)
            echo "Skipping $file"
            continue;;
    esac
    set +e
    sed "${sedflags[@]}" -e "s/stactools-sentinel3/stactools-${name}/g" $file
    sed "${sedflags[@]}" -e "s/stactools\.sentinel3/stactools.${underscore_name}/g" $file
    sed "${sedflags[@]}" -e "s/stactools_sentinel3/stactools_${underscore_name}/g" $file
    sed "${sedflags[@]}" -e "s;stactools/sentinel3;stactools/${underscore_name};g" $file
    sed "${sedflags[@]}" -e "s/sentinel3cmd/${spaceless_name}/g" $file
    sed "${sedflags[@]}" -e "s/sentinel3/${name}/g" $file
    set -e
done

if [ -d src/stactools/sentinel3 ]; then
    git mv src/stactools/sentinel3 src/stactools/$underscore_name
fi

echo "Rename complete"
